# Generated by Django 5.0.3 on 2024-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percustoemr',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
